sudo: required
language: bash
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_569adc779ef7_key -iv $encrypted_569adc779ef7_iv
  -in book_gamma.jks.enc -out book_gamma.jks -d
before_script:
- docker build --build-arg release_flag=yes --build-arg keystore_pass=KEYSTORE_PASS --build-arg alias_name=$ALIAS_NAME --build-arg alias_pass=$ALIAS_PASS -t test ./
script:
- #docker run test
before_deploy:
- docker run --name release test ./gradlew assembleRelease
- docker cp release:/project/app/build/outputs/apk/app-release.apk BookGamma-$TRAVIS_TAG.apk
deploy:
  provider: releases
  api_key:
    secure: mQ6V1N+5bXcpGDfMx4Os/hX6YS0IUXW6EJbvyC/2M3dEHd0BbMDrGkrFceg0cfYsyKY7fgjf47fccpFsUwtVQab5M47tQWfbY7eo/jIxy2kVqHcuFkZJC9kmM5GwJL37bzeXrCH6vJzklCAhF/UWwXwrI+Ea50ql6yzSGTPxq2BLFDlZxNJDPMCn6pN0poOOpZq0PET5gry43FKOHj3l47YMkFVx3TNvT/34LUsgfV71I1Ruu9A2A/YTofjLQZLkHwFz6jmD9mfHv1XiO/tE1ceioVHlx+blHxk9A4k1z8984ucVrya3iAXFefey0e1kCsp9CM/WMDXmo/72B+T7NS3DkGRD10JUZxNrjzsoMTKn34LKLVh7vBG/83GYNfHjwXjc+iOln4Y6uQC/B7yuLg5vzl3XaXq3RIVdXBOt7+ZJYViiPMbqOvqHr8LA7P0KAXYjSVyga0Mxi4Iv8k/+8qs6b4Z3Sx/22VHISONe2XZya9upxbTVdFgVlXMhMt1AimZWXKkXA+RpxVyAtmjKn2GqgT2EcZAxgbcEYiKrQKzDa9bTLHu0vvFuec4jdGQoDk7FRIKaLF0idlxxF3Yzk/HcDqNNfsTze98R7UxJCzcAuXaBfdUBQ+31Xh87gbT/wBwtPxAN7DNn6D26AWDe2RwPK010DT/7BFa2nZkD6pY=
  file: BookGamma-$TRAVIS_TAG.apk
  skip_cleanup: true
  on:
    tags: true
    repo: XJGamma/BookGamma
env:
  global:
    secure: Wh+Lq1URehpyJ/JEWpiCKMFXkzXPNy0XxDDSVL8OjNUQHVlZ54ZsxB9gmsUrIPh/RCiCj1vH/ba3InPIp8tHIMvCaE7eCfsh2a1oWLCAQsXq3O9TFJCrKPXj3ZJXbkCocXbWdpSQ1oLegnesNaBKga6aJMl2vDpL4cH15LRSo4fIqEPwNYva4ferVMqB5YwUf0+YrToBpURXKdWhyJB//08W84ayf6l05qLLaIuvR15CqqxvUnPmaQc3obqngVVBU6zoA6LCoRnkBFBtYwE8D8TrO7Af9pcfUz86B8oo3bQ83srA95S2iE/BB+x8TiydER2cnj2AgKWxKhQ+2ieKQh/7akvfgpG5kuNHTCCz5EHv5HZAcVUsn+F0GvWSPWKom7RA0bDRSZNdDgLzWuk3SETH3kdGE3bdBvYavfgKjB2pMiX/VG3h0aOaNlpFpbnIc9us6GFgHdIQ3nXp9iYod+oqsLegY/7x9JKQtevVvUss9Zd4bPZKGVyppSSU3hX6Jtpao0EwECuP/ZOf5c2Ejp1LYOoFfJ5k6yHESk45Ru/lZC/AO48bV65CFNedz7oNUMGD/ezTc9ia9DFEnczSwKuGv4JiBn/wWc+Ttug+uOfNFjDXgLoPUfdwzB1YEmtI+gDIEl85gnSjdxm2O3/Yl/g01PxwyqoYTx3hUeBWsV4=
