sudo: required
language: bash
services:
- docker
before_script:
- openssl aes-256-cbc -K $encrypted_569adc779ef7_key -iv $encrypted_569adc779ef7_iv -in book_gamma.jks.enc -out book_gamma.jks -d
- docker build --build-arg release_flag=yes --build-arg travis_tag=$TRAVIS_TAG --build-arg keystore_pass=$KEYSTORE_PASS --build-arg alias_name=$ALIAS_NAME --build-arg alias_pass=$ALIAS_PASS -t test ./
script:
- docker run test ./gradlew assembleDebug test
before_deploy:
- docker run --name release test ./gradlew assembleRelease
- docker cp release:/project/app/build/outputs/apk/app-release.apk BookGamma-$TRAVIS_TAG.apk
deploy:
  provider: releases
  api_key:
    secure: mQ6V1N+5bXcpGDfMx4Os/hX6YS0IUXW6EJbvyC/2M3dEHd0BbMDrGkrFceg0cfYsyKY7fgjf47fccpFsUwtVQab5M47tQWfbY7eo/jIxy2kVqHcuFkZJC9kmM5GwJL37bzeXrCH6vJzklCAhF/UWwXwrI+Ea50ql6yzSGTPxq2BLFDlZxNJDPMCn6pN0poOOpZq0PET5gry43FKOHj3l47YMkFVx3TNvT/34LUsgfV71I1Ruu9A2A/YTofjLQZLkHwFz6jmD9mfHv1XiO/tE1ceioVHlx+blHxk9A4k1z8984ucVrya3iAXFefey0e1kCsp9CM/WMDXmo/72B+T7NS3DkGRD10JUZxNrjzsoMTKn34LKLVh7vBG/83GYNfHjwXjc+iOln4Y6uQC/B7yuLg5vzl3XaXq3RIVdXBOt7+ZJYViiPMbqOvqHr8LA7P0KAXYjSVyga0Mxi4Iv8k/+8qs6b4Z3Sx/22VHISONe2XZya9upxbTVdFgVlXMhMt1AimZWXKkXA+RpxVyAtmjKn2GqgT2EcZAxgbcEYiKrQKzDa9bTLHu0vvFuec4jdGQoDk7FRIKaLF0idlxxF3Yzk/HcDqNNfsTze98R7UxJCzcAuXaBfdUBQ+31Xh87gbT/wBwtPxAN7DNn6D26AWDe2RwPK010DT/7BFa2nZkD6pY=
  file: BookGamma-$TRAVIS_TAG.apk
  skip_cleanup: true
  on:
    tags: true
    repo: XJGamma/BookGamma
env:
  global:
    secure: B7Mhs33HuLKp8+3LTG77bzuy5d3BXuCWVZlyYfzWRQfIbklfm0L51D9LyWU88/bMWIZ12AtSf2a62Pet1zmGHZspijqY5ohSDxDuE+XcNptUZMej7vN1fsa+VMIETiucTt3JWpvXutelgGNOmd15ci0eYHHcCkOOQyJKMMigkgkV1pkTbwlJLX1hxCPvbdpdExPb0TNhlGQL+0Ib+ivY+54vCU4w6gKuvJX0qxCsKtoNEgJY4D8BJaRrqdEMVXqU58jcMQMpBhN32Qd1Vltv7zyHwtkizEHvlHOR1wTwyYGsR6ztzbOJo0GEfNCbSW6s0iY92aQ/Num04Se61YoKjyHdyODPXkSiUcUGiBKc10SBOgPAkY19k7bHSnISPl4m7q/th9uPbJwRld0rs7S+m5dBIpAyzvMw63mGS7NPAhdKMH/pSuJGPE9Si3+7yM5K6eK5QxINwUKF28HNmcJnSld6FTe5ChQ1Yft4zly9lPCFZf6iBSjw5nxVG1npoHZDaUAGyPfevL5ykvM+MQICIwGIzx9tY+bfWzN5Uk2mzr6ylayvapTAKXxL1TQQfxbM+s35twgIFLjLZ8ijf0CsDhjtCPVnTCxjcG4HotnFEy+FS/qoVAk1eoP3+FAzjKhBddmDycPnGic8gh+TtejwPXU177A8yB+H9iJWRsCoQqw=
