sudo: required
language: bash
services:
  - docker
before_script:
  - docker build -t test ./
script:
  - docker run test ./gradlew assembleDebug
  - docker run test ./gradlew test
  - docker run test ./gradlew cAT
