#!/usr/bin/env bash

# From https://github.com/ksoichiro/dockerfiles/blob/master/android-emulator/start-emulator

if [ $# -gt 0 ]; then
  CMD=$1
  echo "Starting emulator..."
  emulator64-arm -avd test -no-skin -no-audio -no-window -gpu off &
  android-wait-for-emulator
  $CMD
else
  echo "No command is specified"
fi
